### ISSUE TITLE
sharing data(or data portrait) to server

### ISSUE THREAD

**Issue by harae37** [net-art-and-cultures/data-bodies#10]

**Comment by jwham92** [comment]
Hi @Steve-luo , when will you pull request JSON file?

**Comment by jluo98** [comment]
what json file

**Comment by jwham92** [comment]
oh sorry maybe I said wrong the one you are working on, the visualization data that goes into the popup window.

In popup.js

saveButton.addEventListener('click', () => {
  const data = new FormData()
  data.append('image', **The one you are working on**)
  fetch('http://localhost:8000/api/image-upload', { method: 'POST', body: data })
})

**Comment by jluo98** [comment]
I'm working on it right now :)

**Comment by jwham92** [comment]
Okay! Thanks for letting me know. I'll working on it after you upload the code.
