### ISSUE TITLE
I just found a mouse movement visualization application

### ISSUE THREAD

**Issue by jwham92** [net-art-and-cultures/data-bodies#17]
**IOGraph** — is an application that turns mouse movements into a modern art. The idea is that you just run it and do your usual day stuff at the computer. Go back to IOGraph after a while and grab a nice picture of what you’ve done!

Design, idea, content, programming: Anatoly Zenkov
Admin, JavaScript, support, development, HTML/CSS Coding, Django, Python.

https://www.andreyshipilov.com/projects/iographica-2/

**Comment by nbriz** [comment]
very interesting. definitely something to take a look at && draw some inspiration from, but i wouldn't necessarily use this code for the project. instead, ask urselves how is this similar to what u want to make? how is it different? what does it do well (so u can try to do the same)? && what does it do poorly (so u can try to improve on that).

in terms of technical execution, i suggest using the "[mouse move](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousemove_event)" event (which is a native browser API) to get the mouse data && then either the [Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) or [p5.js](https://p5js.org/) (which is itself is built on the canvas api) to create images from the mouse data.
