### ISSUE TITLE
How to make Browser Extensions!

### ISSUE THREAD

**Issue by jwham92** [net-art-and-cultures/data-bodies#3]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions

**What are extensions?**
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/What_are_WebExtensions

**Your first extension**
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

**Your second extension**
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_second_WebExtension

*YouTube Tutorials*
https://www.youtube.com/watch?v=P0ugObgYohY

**Comment by jwham92** [comment]
@net-art-and-cultures/data-bodies @net-art-and-cultures/the-toolkit 
This is really helpful to understand the way to make Add on Extensions. Shiffman uses Chrome extensions tho, the structures of the scripts are almost same! : )

_youtube tutorials_
https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bL9VOMT65ahNEri9uqLWfS
_shiffman.net_
http://shiffman.net/a2z/chrome-ext/

**Comment by nbriz** [comment]
great find! i didn't know he had an addon course! 
don't forget to tag ur team if u want to notify them >> @net-art-and-cultures/data-bodies
