### ISSUE TITLE
Write Statement

### ISSUE THREAD

**Issue by nbriz** [net-art-and-cultures/data-bodies#31]
update the README.md && update the about page with the statement

**Comment by jwham92** [comment]
Hi guys, sorry for the delay.
Here is a draft statement of our project. Feel free to suggest or revise the document! @net-art-and-cultures/data-bodies 
https://docs.google.com/document/d/1u5VhElFzK4vvQI-zl6PMPmL6fREoyoE_wmM_rjGDmuM/edit?usp=sharing
